name: SwiftLint & SwiftFormat Auto-Fix

on:
  pull_request:
    branches: [ main ]

jobs:
  lint_and_fix:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SwiftLint and SwiftFormat
        run: brew install swiftlint swiftformat

      - name: Run SwiftLint (warnings only)
        run: swiftlint

      - name: Run SwiftFormat (fix issues)
        run: swiftformat .

      - name: Commit changes if needed
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-format code with SwiftFormat"
        continue-on-error: true
